{{ Html::style('css/vendor.bundle.addons.css') }}
{{ Html::style('css/vendor.bundle.base.css') }}
{{ Html::style('css/icheck/all.css') }}
{{ Html::style('css/demo_1/style.css') }}
{{ Html::style('css/shared/style.css') }}
{{ Html::style('iconfonts/flag-icon.css') }}
{{ Html::style('iconfonts/ionicons.css') }}
{{ Html::style('iconfonts/materialdesignicons.css') }}
{{ Html::style('iconfonts/typicons.css') }}
{{ Html::style('css/wickedpicker.css') }}
{{ Html::style('https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css') }}